name: plugin_global
description: A global flutter plugin project.
version: 0.0.1
publish_to: none

homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  # adding dependency (path) to plugins
  plugin_linux:
    path: ../plugin_linux

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
 
  plugin:
    platforms:   
      linux:
          default_package: plugin_linux

      #some_platform:
      #  pluginClass: somePluginClass
    